@startuml

abstract class PetProduct {
  - name
  - type
  - category
  - price
  - tax

  + __construct()
  + getName()
  + getType()
  + getCategory()
  + getPrice()
  + getTax()
  
  abstract calculateTax()
  abstract calculateSalePrice()
}

class PetFood extends PetProduct {
  - expiration

  + __construct()
  + getExpiration()
  + calculateExpiration()
  + calculateTax()
  + calculateSalePrice()
}

class PetToys extends PetProduct {
  + __construct()
  + calculateTax()
  + calculateSalePrice()
}

@enduml

