@startuml

abstract class PetProduct {
  - name
  - type
  - category
  - price
  - tax
  -brand
  -cost
  -profitMargin

  + __construct()
  + getName()
  + getType()
  + getCategory()
  + getPrice()
  + getTax()
  +getBrand
  +getCost
  +getProfitMargin
  abstractcalculatePrice()
  abstract calculateTax()
  abstract calculateSalePrice()
}

class PetFood extends PetProduct {
  - expiration

  + __construct()
  + getExpiration()
  + calculateExpiration()
  +abstractcalculatePrice()
  + calculateTax()
  + calculateSalePrice()
  + calculateProfit
  +calculateInventory
  +calculateShelfTime
}

class PetToy extends PetProduct {

  + __construct()
  +abstractcalculatePrice()
  + calculateTax()
  + calculateSalePrice()
  + calculateProfit
  +calculateInventory
  +calculateShelfTime
}

@enduml

