
@startuml
Type --|> Product
Category --|> Product
Brand --|> Product
Category --|> Product
PetFoodExpiration --|> Product
PetToySize --|> Product

abstract class Product {
  -product_id
  -product_type
  -brand_id
  -price
  construct()
  addTax()
  calculateSalePrice()
}

class Type {
  type_id
  type
}

class Category {
  -category_id
  -category
}

class Brand {
  -brand_id
  -name
}

class PetFoodExpiration {
  -expiration_id
  -expirationdate
}

class PetToySize {
  -size_id
  -size
}

@enduml
