
@startuml
Type --|> Product
Category --|> Product
Brand --|> Product
 Price --|> Product 
PetFoodExpiration --|> Product
PetToySize --|> Product

abstract class Product {
  -productID
  -name
  -typeID
  -categoryID
  -brandID
  -pricingID
}

class Type {
  typeID
  type
}

class Category {
  -categoryID
  -category
}

class Brand {
  -brandID
  -name
}
class Price {
  -pricingID
  -price
  construct()
  addTax()
  calculateSalePrice()
  }

class PetFoodExpiration {
  -expiration_id
  -expirationdate
}

class PetToySize {
  -size_id
  -size
}

@enduml
