
@startuml

Pet extends to Product
Category --|> Product
Brand --|> Product
Pricing --|> Product
Tax --|> Product
ProductCategory --|> Product

abstract class Product {
  -product_id: int
  -product_type: string
  -brand_id: int
  -pricing_id: int
  __construct()
  +calculateTax(): double
  +getSalePrice(): double
}

class Pet {
  -pet_id: int
  -pet: string
}

class Category {
  -category_id: int
  -category: string
}

class Brand {
  -brand_id: int
  -name: string
}

class Pricing {
  -pricing_id: int
  -purchase_price: double
  -sale_price: double
  __construct()
  +getPurchasePrice(): double
  +getSalePrice(): double
}

class Tax {
  -tax_id: int
  -qst_rate: double
  -gst_rate: double
}

class ProductCategory {
  -product_id: int
  -category_id: int
}


@enduml
